kind: pipeline
name: sanskrit-parser-api

steps:

# For Custom Docker Registry
- name: sanskrit-parser-api - build docker image
  image: docker:latest
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    DUSER:
      from_secret: docker_user
    DPASS:
      from_secret: docker_pass
    SERVER_DOMAIN:
      from_secret: server_domain
    DRONE_TAG: ${DRONE_TAG}
  commands:
    - docker login -p $DPASS -u $DUSER docker.$SERVER_DOMAIN
    - docker build --no-cache -t docker.$SERVER_DOMAIN/home/sanskrit-parser-api:latest -f Dockerfile.api .
    - docker push docker.$SERVER_DOMAIN/home/sanskrit-parser-api:latest
  when:
    branch:
    - docker

# Deploy app using ansible
- name: apply ansible playbook
  image: plugins/ansible:1
  environment:
    ansible_vault_pass:
      from_secret: ansible_vault_pass
    # KUBECONFIG_FILE_CONTENT:
    #   from_secret: rke2_kubeconfig
  settings:
    playbook: .ansible/playbook.yml
    # galaxy: .ansible/requirements.yml
    inventory: .ansible/inventory
    private_key:
      from_secret: host_ssh_key
    vault_password:
      from_secret: ansible_vault_pass
    extra_vars:
      git_tag: ${DRONE_TAG}
  when:
    branch:
    - docker

# Finally common tasks for all steps
- name: notify
  image: plugins/slack
  settings:
    channel: pipelines
    webhook:
      from_secret: pipeline_notifier
    icon_url: https://unsplash.it/48/48/?random
    # image_url: https://unsplash.it/256/256/?random
    template: >
      {{#if build.pull }}
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
      {{else}}
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
      {{/if}}
      Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
      Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
      Author: {{ build.author }}
      <{{ build.link }}|Visit build page ↗>
  when:
    status: [ success, failure ]

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock