servers:
  hosts:
    host-ct:
      ansible_host: kube.local.io
      ansible_connection: ssh
      ansible_ssh_user: "{{ ssh_user }}"
      ansible_python_interpreter: /usr/bin/python3
      # ansible_ssh_private_key_file: "~/.ssh/id_rsa_hsrv"
